### ISSUE TITLE
City Builder doesn't store cargo.

### ISSUE THREAD

**Issue by RhavensEye** [TheDude-gh/simplecb#1]

**Comment by RhavensEye** [comment]
It seems to only store FIRS's cargo (like food), but doesn't store passangers, mail, or coal. (Playing with FIRS 4 steeltown)

**Comment by TheDude-gh** [comment]
Please provide more details

**Comment by RhavensEye** [comment]
Well sure, so if I'm using "FIRS 4 Steeltown" preset (chosen instead of custom in game script settings) non FIRS resorces like "passangers" are being shown in town requirements and they can't be stored. For FIRS resorces "like food" it shows storage: x, required/delivered: x. But for base game stuff it just shows required/delivered. 
Everything still works fine on custom settings.

**Comment by TheDude-gh** [comment]
I see. Well, that is not bug that is just how the preset is set.

Every preset has storage for passengers and mail set to zero (sometimes also other cargo, like coal). It's sort of realistic, since some cargo makes sense to be in storage, but you would not lock people or mail for another month.

You can see presets in [minor.nut](https://github.com/TheDude-gh/simplecb/blob/f7b1fde6b979183508bffe71ffbd6914d2f3fb53/minor.nut#L258) file.

If you want to store passengers, use custom cargo settings.
